# Generated by Django 2.2.4 on 2019-08-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=500)),
                ('lattes_link', models.CharField(max_length=500)),
                ('facebook_link', models.CharField(max_length=500)),
                ('instagram_link', models.CharField(max_length=500)),
                ('twitter_link', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=600)),
                ('published_at', models.DateField()),
                ('web_link', models.CharField(max_length=500)),
                ('first_author', models.BooleanField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Researcher')),
            ],
        ),
    ]
