# Generated by Django 2.2.4 on 2019-08-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='photos/posts')),
                ('is_cover', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='photo',
            field=models.ImageField(upload_to='photos/researchers/'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
