# Generated by Django 2.2.4 on 2019-08-09 13:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190809_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField(max_length=600)),
                ('is_cover', models.BooleanField()),
                ('photo', models.ImageField(upload_to='photos/short_posts/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
