# Generated by Django 2.2.4 on 2019-08-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190809_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpost',
            name='web_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
