# Generated by Django 2.2.4 on 2019-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_shortpost_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='is_cover',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
