# Generated by Django 2.2.4 on 2019-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_researcher_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
