# Generated by Django 2.2.4 on 2019-08-09 19:49

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_post_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
